version: "3"
services:
# Web server
  nginx:
    image: nginx:1.15.7-alpine
    container_name: laravel-nginx
    volumes:
      - ${PWD}/src:/src
      - ${PWD}/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
  php:
    build: ./php
    container_name: "laravel-php"
    volumes:
      - ${PWD}/src:/src
      - ${PWD}/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    working_dir: /src
  postgres:
    restart: always
    image: postgres:alpine
    container_name: "laravel-postgres"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 15432:5432
  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - ./pgadmin:/var/lib/pgadmin/storage
    ports:
      - "80:80"
      - "443:443"
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@hoge.com"
      PGADMIN_DEFAULT_PASSWORD: "changeme"